* ping

diff --git a/capsmanqr b/capsmanqr
--- a/capsmanqr
+++ b/capsmanqr
@@ -63,9 +63,15 @@ mkdir -p "$donde"/qr
 clear
 
 for i in ${ips[@]}; do
+	ping -A -c 5 $i > /dev/null
+	if [[ $? = 0 ]]; then
+		echo "IP: $i"
+		echo "IP: $i" >> "$archi"
+	else
+		echo "ERROR: $i no esta disponible."
+		exit 1
+	fi
 	clave=$(dd if=/dev/urandom bs=1 count=64 2>/dev/null | base64 -w 0 | tr -dc _A-Z-a-z-0-9 | cut -c 1-8)
-	echo "IP: $i"
-	echo "IP: $i" >> "$archi"
 	echo "Clave: $clave"
 	echo "Clave: $clave" >> "$archi"
 	echo "=========================" >> "$archi"
diff --git a/mtkback b/mtkback
--- a/mtkback
+++ b/mtkback
@@ -54,8 +54,14 @@ fi
 clear
 
 for i in ${ips[@]}; do
-	echo "IP: $i"
-	echo "IP: $i" >> "$archi"
+	ping -A -c 5 $i > /dev/null
+	if [[ $? = 0 ]]; then
+		echo "IP: $i"
+		echo "IP: $i" >> "$archi"
+	else
+		echo "ERROR: $i no esta disponible."
+		exit 1
+	fi
 	echo "=========================" >> "$archi"
 	if [[ "$sshport" == "22" ]]; then
 		echo "Creando Backup"
